name: Deploy Frontend

on:
  push:
    branches: [ main ]

# Add this permissions block
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}  # Uses the default token