name: Deploy Frontend

on:
  push:
    branches: [ main ]
    # Optionally add path filters if you want
    # paths:
    #   - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend
          branch: gh-pages